Herotomkovid
NatVladyslav/project-UkrainianClothes pull request #19
Opened 2024-05-26 18:28 UTC by OleksandrTom

Привіт, доробив секцію. Виправив розміри картинок та змінив розташування svg іконки. 
Також попробував зробити стрілочку, перевірив - ретина працює.

2024-05-26 19:49 UTC, NatVladyslav requested changes

2024-05-26 19:49 UTC, NatVladyslav commented on src/css/hero.css
> +    letter-spacing: -0.03em;
Додайте font-weight: 400;
Також колір color: #fcf9f9

2024-05-26 19:49 UTC, NatVladyslav commented on src/css/hero.css
> +.hero-icon-btn:hover {
Тут можна зробити щоб  не просто на стрілку, а прямо коли на кнопку наводять. Замінити hero-icon-btn:hover на hero-btn:hover (Так як це реалізовано в секції Ордер)

2024-05-26 19:49 UTC, NatVladyslav commented on src/css/hero.css
> + transform: rotate(60deg);
rotate краще зробити так як в секції Order 30deg

2024-05-27 08:13 UTC, OleksandrTom commented
Виправив текст на стрілочку на кнопці

2024-05-27 09:21 UTC, closed without merging